[package]
authors = ["Safin Singh <safinsingh.dev@gmail.com>"]
edition = "2018"
name = "gptinfo"
version = "1.0.0"

[dependencies]
anyhow = "1.0.34"
colored = "2.0.0"
clap = "3.0.0-beta.2"
lazy_static = "1.4.0"
nix = "0.19.1"
thiserror = "1.0.22"
